blank_issues_enabled: false
contact_links:
  - name: Discussion
    url: https://github.com/rbeucher/access-moppy-qc-registry/discussions
    about: Not sure which template to use? Start a discussion.
